# Generated by Django 6.0.1 on 2026-02-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_taskdata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdata',
            name='priority',
            field=models.IntegerField(choices=[(1, 'HIGH'), (2, 'MEDIUM'), (3, 'LOW')], default=2),
        ),
    ]
